export const entries = [
  {
    id: 'desosser-poulet',
    type: 'tip',
    category: 'Techniques',
    title: 'Désosser un poulet entier',
    titleItalic: 'un poulet entier',
    titleBase: 'Désosser',
    subtitle: 'les différents morceaux',
    illustration: 'chicken-breakdown',
    ingredients: [
      { label: 'un poulet entier vidé et élevé en plein air, peau un peu jaune' },
    ],
    video: 'https://www.youtube.com/embed/-oefcSkw2ds',
    steps: [
      { text: 'Poitrine vers le haut, tête vers soi, fais une incision entre chaque cuisse et la poitrine.' },
      { text: 'Déjante les cuisses du poulet et découpe en longeant le thorax (bien dégager le sot-l\'y-laisse).' },
      { text: 'Retire les petites ailes au niveau du coude (déjante si nécessaire).' },
      { text: 'Découpe les blancs en longeant le bréchet (os au milieu de la poitrine) sur toute la longueur et en prenant les petits pilons restants des ailes.' },
      { text: 'Enlève le gras si besoin, sinon c\'est déjà finit chef.' },
      { text: 'Mettre au frais directement et garde bien les os / carcasse pour faire un bouillon (sinon j\'te frappe...).' },
    ],
    notes: 'Le couteau, toujours pointé en face de toi et toujours couper en tirant et pas en poussant (comme ça tu n\'abîmes pas tes belles mains mon chou <3).',
  },
  {
    id: 'bouillon-poulet',
    type: 'recipe',
    category: 'Bases & sauces',
    title: 'Bouillon de poulet',
    titleBase: 'Bouillon',
    titleItalic: 'de poulet',
    time: '3h – 10h',
    difficulty: 'Facile',
    servings: 4,
    illustration: 'broth',
    ingredients: [
      { label: 'Une carcasse de poulet' },
      { label: 'Des légumes au choix (oignons, carottes, céleris, ...)' },
      { label: 'Des herbes au choix (thym, origan, laurier, ...)' },
      { label: 'De l\'eau en bonne quantité' },
      { label: 'Un liquide pour déglasser (eau, armagnac, vin blanc, ...)' },
      { label: 'Huile ou matière grasse' },
    ],
    steps: [
      { text: 'Fais chauffer le four à 160°C, mets ta carcasse dans le plat creux et fait lui prendre un petit bain de soleil jusqu\'à ce qu\'elle soit bien bronzée.' },
      { text: 'Découpe tes légumes grossièrement (tu peux même laisser la peau, mais lave-la quand même).' },
      { text: 'Quand ta carcasse commence à être bien brune, fais chauffer ta casserole, ajoute de l\'huile ou ta matière grasse et fais revenir tes légumes.' },
      { text: 'Sors ta carcasse du four et ajoute-la dans la casserole.' },
      { text: 'Déglasse ton plat sorti du four avec ton liquide puis ajoute les sucs à ton bouillon.' },
      { text: 'Ajoute de l\'eau froide (environ 1cm au dessus de ce qu\'il y a dans ta casserole), tes herbes et des glaçons. Les glaçons et l\'eau froide vont aider à libérer les arômes.' },
      { text: 'Fais chauffer jusqu\'à frémissement.' },
      { text: 'De l\'écume va se former sur le dessus les quelques premières minutes, enlève-la avec ta louche.' },
      { text: 'Mets le couvercle et laisse frémir en venant remuer de temps en temps pendant 3h à 10h (plus tu laisses, plus les arômes se libèrent — mais avec 3h, l\'essentiel est déjà là).' },
      { text: 'Filtre ton bouillon pour ne garder que le liquide (tu peux garder les légumes pour une soupe ou un accompagnement) et attends qu\'il tiédisse (tu peux accélérer ça avec un bain-marie dans de l\'eau froide).' },
      { text: 'Mets-le au frigo, une couche de gras peu dégueu devrait se former au dessus, enlève-la.' },
      { text: 'Assaisonne ton bouillon à ton goût (ou garde-le comme ça si t\'en es satisfait).' },
    ],
    notes: 'Le bouillon se garde 4 à 6 jours au frigo mais peut être congelé pour être gardé bien plus longtemps.',
  },
  {
    id: 'cuire-riz',
    type: 'tip',
    category: 'Techniques',
    title: 'Cuire',
    titleItalic: 'correctement le riz',
    titleBase: 'Cuire',
    illustration: 'rice-bowl',
    ingredients: [
      { label: 'Accompagnement', base: 50, unit: 'g' },
      { label: 'Plat principal', base: 100, unit: 'g' },
    ],
    steps: [
      { text: 'Rince le riz 3–4 fois à l\'eau froide dans la casserole, jusqu\'à ce que l\'eau soit à peu près claire pour enlever l\'excès d\'amidon.' },
      { text: 'Tasse bien le riz au fond de la casserole. Pose ton gros doigt à la verticale sur le riz, sans l\'enfoncer dedans, et remplis d\'eau froide jusqu\'à la première articulation de ton doigt.', illustration: 'finger-measure' },
      { text: 'Feu au max, remue de temps en temps et attends que ça bouille bien.' },
      { text: 'Remue une bonne fois, baisse au minimum (sans éteindre le feu) et couvre pendant 10–15 min.' },
      { text: 'SANS ENLEVER LE COUVERCLE. Coupe le feu complètement et laisse reposer 5 min.' },
      { text: 'C\'est bon beau gosse, ton riz est prêt.' },
    ],
    notes: 'La méthode du doigt marche pour n\'importe quelle quantité — c\'est de la physique, pas de la magie. Ça a nourri la moitié de la planète avant que les verres doseurs existent.',
  },
  {
    id: 'carbonara',
    type: 'recipe',
    category: 'Plats',
    title: 'Pâtes à la carbonara',
    titleBase: 'Pâtes',
    titleItalic: 'à la carbonara',
    time: '20 min',
    difficulty: 'Moyen',
    tags: ['Sans crème', '65 °C'],
    illustration: 'carbonara',
    video: 'https://www.youtube.com/embed/SsUGomHw85o',
    ingredients: [
      { label: 'de spaghetti (ou les pâtes que tu préfères, ça marche pareil)', base: 100, unit: 'g' },
      { label: 'de guanciale', base: 40, unit: 'g' },
      { label: 'jaune d\'œuf (gros calibre)', base: 1 },
      { label: 'de pecorino romano', base: 30, unit: 'g' },
      { label: 'de grana padano', base: 15, unit: 'g' },
      { label: 'Poivre noir du moulin, sans compter' },
      { label: 'Du gros sel pour l\'eau des pâtes — la main légère' },
    ],
    steps: [
      { text: 'Retire la couenne du guanciale et détaille-le en gros cubes.' },
      { text: 'Monte ta poêle à fond, et une fois qu\'elle est bien chaude, redescends sur feu doux avant d\'y jeter le guanciale.' },
      { text: 'Laisse-le rendre sa graisse et frire dedans, tranquillement, jusqu\'à ce que les faces soient dorées et croustillantes. Tu n\'ajoutes aucune matière grasse — il se débrouille tout seul comme un grand.' },
      { text: 'Pendant que ça cuit, sépare les blancs des jaunes et dépose les jaunes dans un cul-de-poule qui pourra passer en bain-marie.' },
      { text: 'Râpe le pecorino et le grana padano, ajoute-les aux jaunes avec une bonne dose de poivre noir.' },
      { text: 'Quand le guanciale est bien doré, verse un peu de sa graisse dans le cul-de-poule (jette le reste) et réserve les cubes de côté.' },
      { text: 'Fouette les jaunes, les fromages et la graisse, puis détends avec un peu d\'eau de cuisson bien chaude sans arrêter de fouetter, jusqu\'à obtenir une crème lisse.' },
      { text: 'Fais cuire les pâtes dans une eau légèrement salée — moelleuses, pas al dente.' },
      { text: 'Verse les pâtes dans le cul-de-poule avec encore un filet d\'eau de cuisson, puis pose le tout au-dessus de l\'eau frémissante : te voilà en bain-marie.' },
      { text: 'Vise les 65 °C. À cette température les jaunes prennent juste ce qu\'il faut et le fromage devient ultra crémeux — au-dessus, tu fais une omelette et tu pleures. Fouette sans t\'arrêter.' },
      { text: 'Ajoute le guanciale réservé et fouette encore un peu pour tout lier.' },
      { text: 'Dresse dans l\'assiette, pecorino râpé par-dessus et un dernier tour de moulin à poivre. Buon appetito chef.' },
    ],
    notes: 'Zéro crème dans une carbonara — le crémeux vient uniquement des jaunes, du fromage et de l\'eau de cuisson. Sale l\'eau d\'une main très légère : entre le pecorino et le guanciale, c\'est déjà bien assez salé comme ça. Et si tes œufs sont petits, compte plutôt 1,5 jaune par personne.',
  },
  {
    id: 'rochers-coco',
    type: 'recipe',
    category: 'Desserts',
    title: 'Rochers coco',
    titleBase: 'Rochers',
    titleItalic: 'coco',
    time: '17 min',
    difficulty: 'Facile',
    tags: ['3 ingrédients'],
    illustration: 'coconut-rock',
    // Recette d'origine pour 6 : 125 g de coco, 120 g de sucre, 3 blancs.
    // `base` est la quantité par personne — 125/6 reste écrit tel quel pour que
    // le compteur retombe exactement sur 125 g à 6 pers.
    ingredients: [
      { label: 'de noix de coco râpée', base: 125 / 6, unit: 'g' },
      { label: 'de sucre', base: 20, unit: 'g' },
      { label: 'blanc(s) d\'œuf', base: 0.5 },
    ],
    steps: [
      { text: 'Préchauffe ton four à 200 °C.' },
      { text: 'Balance la noix de coco, le sucre et les blancs d\'œufs dans un cul-de-poule.' },
      { text: 'Fouette le tout jusqu\'à ce que ce soit bien homogène. Pas besoin de monter les blancs, tu mélanges, c\'est tout.' },
      { text: 'Avec une cuillère à café, façonne des petits rochers et dépose-les sur une plaque recouverte de papier cuisson.' },
      { text: 'Enfourne 12 min, jusqu\'à ce qu\'ils soient légèrement colorés. Et voilà chef.' },
    ],
    notes: 'Sors-les dès que les pointes sont dorées : ils finissent de sécher en refroidissant et resteront moelleux au cœur. Si tu attends qu\'ils soient bruns dans le four, tu obtiendras des cailloux (le nom est déjà pris).',
  },
  {
    id: 'beurre-ail-confit',
    type: 'recipe',
    category: 'Bases & sauces',
    title: 'Beurre à l\'ail confit',
    titleBase: 'Beurre',
    titleItalic: 'à l\'ail confit',
    time: '1h',
    difficulty: 'Facile',
    illustration: 'garlic-butter',
    // Quantités fixes : c'est une préparation qui se fait au batch, pas par personne.
    ingredients: [
      { label: 'têtes d\'ail', qty: '2' },
      { label: 'Huile d\'olive, de quoi couvrir les gousses' },
      { label: 'branche de romarin', qty: '1' },
      { label: 'branches de thym', qty: '2' },
      { label: 'de beurre doux, bien mou', qty: '100 g' },
      { label: 'de persil frais haché', qty: '3 c. à soupe' },
      { label: 'Sel, poivre' },
    ],
    steps: [
      { text: 'Préchauffe ton four à 150 °C.' },
      { text: 'Détache toutes les gousses des deux têtes d\'ail.' },
      { text: 'Mets-les dans un ramequin, couvre-les d\'huile d\'olive et ajoute les branches de thym et de romarin.' },
      { text: 'Enfourne 45 min, jusqu\'à ce que l\'ail soit bien fondant.' },
      { text: 'Sors les gousses du ramequin et mets-les dans un bol avec une cuillère à café de l\'huile de cuisson. Garde le reste de l\'huile pour d\'autres recettes — elle est parfumée à l\'ail et au thym, ce serait un crime de la jeter.' },
      { text: 'Écrase l\'ail, ajoute le beurre mou, les 3 cuillères à soupe de persil haché, puis sale et poivre à ton goût.' },
      { text: 'Mélange jusqu\'à obtenir quelque chose de bien homogène, puis direction le frigo.' },
    ],
    notes: 'Roule-le dans du film alimentaire pour en faire un boudin : tu n\'auras plus qu\'à couper des rondelles à la demande. Il se garde une bonne semaine au frigo et se congèle très bien.',
  },
  {
    id: 'cake-citron',
    type: 'recipe',
    category: 'Desserts',
    title: 'Cake au citron',
    titleBase: 'Cake',
    titleItalic: 'au citron',
    time: '1h15',
    difficulty: 'Facile',
    servings: 8,
    tags: ['Citron entier', 'Au mixeur'],
    illustration: 'lemon-cake',
    // Quantités fixes : un cake se fait au moule entier, pas à la part.
    ingredients: [
      { label: 'citron Meyer', qty: '1' },
      { label: 'de sucre', qty: '150 g' },
      { label: 'œufs', qty: '3' },
      { label: 'd\'huile végétale (6 cl)', qty: '4 c. à soupe' },
      { label: 'de lait (6 cl)', qty: '4 c. à soupe' },
      { label: 'de farine', qty: '220 g' },
      { label: 'de levure chimique', qty: '10 g' },
      { label: 'de sucre glace, pour le glaçage', qty: '100 g' },
      { label: 'de jus de citron, pour le glaçage (environ 1 citron pressé)', qty: '2 c. à soupe' },
    ],
    steps: [
      { text: 'Fais bouillir le citron Meyer entier pendant 5 minutes.' },
      { text: 'Coupe-le en dés et retire les graines.' },
      { text: 'Mets le citron, le sucre, les œufs, l\'huile et le lait dans un récipient haut, puis mixe au mixeur plongeant jusqu\'à obtenir un mélange bien lisse.' },
      { text: 'Ajoute la farine et la levure chimique, puis mixe à nouveau jusqu\'à ce que la pâte soit lisse.' },
      { text: 'Verse dans un moule à cake et enfourne à 160 °C pendant 1 heure.' },
      { text: 'Mélange le sucre glace et le jus de citron pour former le glaçage, puis nappe le cake une fois refroidi.' },
    ],
    notes: 'Le citron passe entier dans la pâte, peau comprise — c\'est les 5 minutes d\'ébullition qui lui enlèvent son amertume, donc ne saute pas cette étape. Et attends vraiment que le cake soit froid avant de le napper : sur un cake tiède, le glaçage fond et file directement dans le plat.',
  },
]

export const categories = [
  { id: 'entrees',             label: 'Entrées',                entryIds: [] },
  { id: 'plats',               label: 'Plats',                  entryIds: ['carbonara'] },
  { id: 'accompagnements',     label: 'Accompagnements',        entryIds: [] },
  { id: 'desserts',            label: 'Desserts',               entryIds: ['rochers-coco', 'cake-citron'] },
  { id: 'petit-dejeuner',      label: 'Petit-déjeuner & brunch',entryIds: [] },
  { id: 'bases-sauces',        label: 'Bases & sauces',         entryIds: ['bouillon-poulet', 'beurre-ail-confit'] },
  { id: 'techniques',          label: 'Techniques',             entryIds: ['desosser-poulet', 'cuire-riz'] },
]

export function getFilteredEntries(filterId) {
  if (!filterId) return entries
  const cat = categories.find((c) => c.id === filterId)
  if (cat) return entries.filter((e) => cat.entryIds.includes(e.id))
  return entries
}
