export const entries = [
  {
    id: 'desosser-poulet',
    type: 'tip',
    category: 'Techniques',
    title: 'Désosser un poulet entier',
    titleItalic: 'un poulet entier',
    titleBase: 'Désosser',
    subtitle: 'les différents morceaux',
    illustration: 'chicken-breakdown',
    ingredients: [
      { label: 'un poulet entier vidé et élevé en plein air, peau un peu jaune' },
    ],
    video: 'https://www.youtube.com/embed/-oefcSkw2ds',
    steps: [
      { text: 'Poitrine vers le haut, tête vers soi, fais une incision entre chaque cuisse et la poitrine.' },
      { text: 'Déjante les cuisses du poulet et découpe en longeant le thorax (bien dégager le sot-l\'y-laisse).' },
      { text: 'Retire les petites ailes au niveau du coude (déjante si nécessaire).' },
      { text: 'Découpe les blancs en longeant le bréchet (os au milieu de la poitrine) sur toute la longueur et en prenant les petits pilons restants des ailes.' },
      { text: 'Enlève le gras si besoin, sinon c\'est déjà finit chef.' },
      { text: 'Mettre au frais directement et garde bien les os / carcasse pour faire un bouillon (sinon j\'te frappe...).' },
    ],
    notes: 'Le couteau, toujours pointé en face de toi et toujours couper en tirant et pas en poussant (comme ça tu n\'abîmes pas tes belles mains mon chou <3).',
  },
  {
    id: 'bouillon-poulet',
    type: 'recipe',
    category: 'Bases & sauces',
    title: 'Bouillon de poulet',
    titleBase: 'Bouillon',
    titleItalic: 'de poulet',
    time: '3h – 10h',
    difficulty: 'Facile',
    servings: 4,
    illustration: 'broth',
    ingredients: [
      { label: 'Une carcasse de poulet' },
      { label: 'Des légumes au choix (oignons, carottes, céleris, ...)' },
      { label: 'Des herbes au choix (thym, origan, laurier, ...)' },
      { label: 'De l\'eau en bonne quantité' },
      { label: 'Un liquide pour déglasser (eau, armagnac, vin blanc, ...)' },
      { label: 'Huile ou matière grasse' },
    ],
    steps: [
      { text: 'Fais chauffer le four à 160°C, mets ta carcasse dans le plat creux et fait lui prendre un petit bain de soleil jusqu\'à ce qu\'elle soit bien bronzée.' },
      { text: 'Découpe tes légumes grossièrement (tu peux même laisser la peau, mais lave-la quand même).' },
      { text: 'Quand ta carcasse commence à être bien brune, fais chauffer ta casserole, ajoute de l\'huile ou ta matière grasse et fais revenir tes légumes.' },
      { text: 'Sors ta carcasse du four et ajoute-la dans la casserole.' },
      { text: 'Déglasse ton plat sorti du four avec ton liquide puis ajoute les sucs à ton bouillon.' },
      { text: 'Ajoute de l\'eau froide (environ 1cm au dessus de ce qu\'il y a dans ta casserole), tes herbes et des glaçons. Les glaçons et l\'eau froide vont aider à libérer les arômes.' },
      { text: 'Fais chauffer jusqu\'à frémissement.' },
      { text: 'De l\'écume va se former sur le dessus les quelques premières minutes, enlève-la avec ta louche.' },
      { text: 'Mets le couvercle et laisse frémir en venant remuer de temps en temps pendant 3h à 10h (plus tu laisses, plus les arômes se libèrent — mais avec 3h, l\'essentiel est déjà là).' },
      { text: 'Filtre ton bouillon pour ne garder que le liquide (tu peux garder les légumes pour une soupe ou un accompagnement) et attends qu\'il tiédisse (tu peux accélérer ça avec un bain-marie dans de l\'eau froide).' },
      { text: 'Mets-le au frigo, une couche de gras peu dégueu devrait se former au dessus, enlève-la.' },
      { text: 'Assaisonne ton bouillon à ton goût (ou garde-le comme ça si t\'en es satisfait).' },
    ],
    notes: 'Le bouillon se garde 4 à 6 jours au frigo mais peut être congelé pour être gardé bien plus longtemps.',
  },
  {
    id: 'cuire-riz',
    type: 'tip',
    category: 'Techniques',
    title: 'Cuire',
    titleItalic: 'correctement le riz',
    titleBase: 'Cuire',
    illustration: 'rice-bowl',
    ingredients: [
      { label: 'Accompagnement', base: 50, unit: 'g' },
      { label: 'Plat principal', base: 100, unit: 'g' },
    ],
    steps: [
      { text: 'Rince le riz 3–4 fois à l\'eau froide dans la casserole, jusqu\'à ce que l\'eau soit à peu près claire pour enlever l\'excès d\'amidon.' },
      { text: 'Tasse bien le riz au fond de la casserole. Pose ton gros doigt à la verticale sur le riz, sans l\'enfoncer dedans, et remplis d\'eau froide jusqu\'à la première articulation de ton doigt.', illustration: 'finger-measure' },
      { text: 'Feu au max, remue de temps en temps et attends que ça bouille bien.' },
      { text: 'Remue une bonne fois, baisse au minimum (sans éteindre le feu) et couvre pendant 10–15 min.' },
      { text: 'SANS ENLEVER LE COUVERCLE. Coupe le feu complètement et laisse reposer 5 min.' },
      { text: 'C\'est bon beau gosse, ton riz est prêt.' },
    ],
    notes: 'La méthode du doigt marche pour n\'importe quelle quantité — c\'est de la physique, pas de la magie. Ça a nourri la moitié de la planète avant que les verres doseurs existent.',
  },
  {
    id: 'carbonara',
    type: 'recipe',
    category: 'Plats',
    title: 'Pâtes à la carbonara',
    titleBase: 'Pâtes',
    titleItalic: 'à la carbonara',
    time: '20 min',
    difficulty: 'Moyen',
    tags: ['Sans crème', '65 °C'],
    illustration: 'carbonara',
    video: 'https://www.youtube.com/embed/SsUGomHw85o',
    ingredients: [
      { label: 'de spaghetti (ou les pâtes que tu préfères, ça marche pareil)', base: 100, unit: 'g' },
      { label: 'de guanciale', base: 40, unit: 'g' },
      { label: 'jaune d\'œuf (gros calibre)', base: 1 },
      { label: 'de pecorino romano', base: 30, unit: 'g' },
      { label: 'de grana padano', base: 15, unit: 'g' },
      { label: 'Poivre noir du moulin, sans compter' },
      { label: 'Du gros sel pour l\'eau des pâtes — la main légère' },
    ],
    steps: [
      { text: 'Retire la couenne du guanciale et détaille-le en gros cubes.' },
      { text: 'Monte ta poêle à fond, et une fois qu\'elle est bien chaude, redescends sur feu doux avant d\'y jeter le guanciale.' },
      { text: 'Laisse-le rendre sa graisse et frire dedans, tranquillement, jusqu\'à ce que les faces soient dorées et croustillantes. Tu n\'ajoutes aucune matière grasse — il se débrouille tout seul comme un grand.' },
      { text: 'Pendant que ça cuit, sépare les blancs des jaunes et dépose les jaunes dans un cul-de-poule qui pourra passer en bain-marie.' },
      { text: 'Râpe le pecorino et le grana padano, ajoute-les aux jaunes avec une bonne dose de poivre noir.' },
      { text: 'Quand le guanciale est bien doré, verse un peu de sa graisse dans le cul-de-poule (jette le reste) et réserve les cubes de côté.' },
      { text: 'Fouette les jaunes, les fromages et la graisse, puis détends avec un peu d\'eau de cuisson bien chaude sans arrêter de fouetter, jusqu\'à obtenir une crème lisse.' },
      { text: 'Fais cuire les pâtes dans une eau légèrement salée — moelleuses, pas al dente.' },
      { text: 'Verse les pâtes dans le cul-de-poule avec encore un filet d\'eau de cuisson, puis pose le tout au-dessus de l\'eau frémissante : te voilà en bain-marie.' },
      { text: 'Vise les 65 °C. À cette température les jaunes prennent juste ce qu\'il faut et le fromage devient ultra crémeux — au-dessus, tu fais une omelette et tu pleures. Fouette sans t\'arrêter.' },
      { text: 'Ajoute le guanciale réservé et fouette encore un peu pour tout lier.' },
      { text: 'Dresse dans l\'assiette, pecorino râpé par-dessus et un dernier tour de moulin à poivre. Buon appetito chef.' },
    ],
    notes: 'Zéro crème dans une carbonara — le crémeux vient uniquement des jaunes, du fromage et de l\'eau de cuisson. Sale l\'eau d\'une main très légère : entre le pecorino et le guanciale, c\'est déjà bien assez salé comme ça. Et si tes œufs sont petits, compte plutôt 1,5 jaune par personne.',
  },
]

export const categories = [
  { id: 'entrees',             label: 'Entrées',                entryIds: [] },
  { id: 'plats',               label: 'Plats',                  entryIds: ['carbonara'] },
  { id: 'accompagnements',     label: 'Accompagnements',        entryIds: [] },
  { id: 'desserts',            label: 'Desserts',               entryIds: [] },
  { id: 'petit-dejeuner',      label: 'Petit-déjeuner & brunch',entryIds: [] },
  { id: 'bases-sauces',        label: 'Bases & sauces',         entryIds: ['bouillon-poulet'] },
  { id: 'techniques',          label: 'Techniques',             entryIds: ['desosser-poulet', 'cuire-riz'] },
]

export function getFilteredEntries(filterId) {
  if (!filterId) return entries
  const cat = categories.find((c) => c.id === filterId)
  if (cat) return entries.filter((e) => cat.entryIds.includes(e.id))
  return entries
}
