// Boissons owns its entries outright — cuisine is food only.
export const boissonsEntries = [
  {
    id: 'limoncello',
    type: 'recipe',
    category: 'Boissons',
    title: 'Limoncello',
    titleBase: 'Limoncello',
    time: '2 jours',
    difficulty: 'Facile',
    tags: ['~40°', '~1,6 L'],
    illustration: 'limoncello',
    ingredients: [
      { label: '5 citrons non traités (bios)' },
      { label: '500ml d\'alcool pur à 95%' },
      { label: '600g de sucre' },
      { label: '750ml d\'eau' },
    ],
    steps: [
      { text: 'Lave les citrons et sèche-les avec un torchon propre.' },
      { text: 'Épluche les zestes en faisant bien attention à ne pas prendre le blanc sous la peau — il est trop amer et gâcherait tout.' },
      { text: 'Mets les zestes dans ton bocal et ajoute l\'alcool. Ferme bien.' },
      { text: 'Cache ton bocal dans ta cave et laisse macérer 2 jours.' },
      { text: 'Après 2 jours, fais chauffer l\'eau et le sucre dans une casserole jusqu\'à ce que le sucre soit complètement dissous. Laisse ton sirop refroidir.' },
      { text: 'Filtre l\'alcool pour retirer les zestes.' },
      { text: 'Ajoute ton sirop refroidi à l\'alcool aromatisé et mélange bien.' },
      { text: 'Embouteille et conserve au congélateur.' },
    ],
    notes: 'L\'alcool est à consommer avec modération (non, tu n\'as pas d\'amis qui s\'appelle "modération".',
  },
  {
    id: 'mai-tai',
    type: 'recipe',
    category: 'Boissons',
    title: 'Mai Tai',
    titleBase: 'Mai Tai',
    time: '5 min',
    difficulty: 'Facile',
    servings: 1,
    illustration: 'mai-tai',
    baseLabel: 'Classique',
    ingredients: [
      { label: 'Rhum blanc', base: 4.4, unit: 'cl' },
      { label: 'Triple sec ou Cointreau', base: 2.2, unit: 'cl' },
      { label: 'Jus de citron vert', base: 2.5, unit: 'cl' },
      { label: 'Sirop d\'orgeat', base: 1.5, unit: 'cl' },
      { label: 'Rhum brun', base: 1.5, unit: 'cl' },
    ],
    steps: [
      { text: 'Mets les glaçons, le rhum blanc, la liqueur d\'orange, le sirop d\'orgeat et le jus de citron dans le shaker.' },
      { text: 'Agite doucement pendant environ 3 secondes.' },
      { text: 'Verse dans un verre à whisky.' },
      { text: 'Ajoute le rhum brun sur le dessus.' },
      { text: 'Bonus : décore avec de la menthe ou une tranche de citron vert.' },
    ],
    notes: 'L\'alcool est à consommer avec modération (non, tu n\'as pas d\'amis qui s\'appelle "modération").',
    variants: [
      {
        label: 'Alexandre',
        ingredients: [
          { label: 'Rhum ambré', base: 3, unit: 'cl' },
          { label: 'Rhum blanc', base: 3, unit: 'cl' },
          { label: 'Grand Marnier', base: 2, unit: 'cl' },
          { label: 'Jus de citron', base: 3, unit: 'cl' },
          { label: 'Sirop d\'orgeat', base: 2.5, unit: 'cl' },
        ],
        steps: [
          { text: 'Met tous les ingrédients dans un shaker.' },
          { text: 'Agite à sec vigoureusement pendant 7 secondes (je sais à quoi tu penses mais non, ça veut dire sans glaçons).' },
          { text: 'Rajoute des glaçons et re-agite plus doucement pendant 3 secondes.' },
          { text: 'Verse dans un verre à whisky et déguste.' },
        ],
      },
      {
        label: 'Thomas',
        ingredients: [
          { label: 'Rhum', base: 5, unit: 'cl' },
          { label: 'Triple sec ou Cointreau', base: 1.5, unit: 'cl' },
          { label: 'Sucre de canne', base: 1.5, unit: 'cl' },
          { label: 'Sirop d\'orgeat', base: 1.5, unit: 'cl' },
          { label: 'Jus de citron vert', base: 1.5, unit: 'cl' },
          { label: 'Passoa', base: 1, unit: 'cl' },
          { label: 'Jus d\'orange', base: 5, unit: 'cl' },
          { label: 'Jus d\'ananas', base: 2.5, unit: 'cl' },
        ],
        steps: [
          { text: 'Mets les glaçons dans un verre à whisky.' },
          { text: 'Ajoute les ingrédients.' },
          { text: 'Ajoute du jus d\'orange et d\'ananas selon ton envie.' },
          { text: 'Mélange bien puis déguste chef.' },
          { text: 'Bonus : mets une rondelle d\'orange sur la tranche du verre pour décorer.' },
        ],
      },
    ],
  },
  {
    id: 'porn-star',
    type: 'recipe',
    category: 'Boissons',
    title: 'Porn Star',
    titleBase: 'Porn Star',
    time: '5 min',
    difficulty: 'Facile',
    servings: 1,
    illustration: 'porn-star',
    ingredients: [
      { label: 'Rhum blanc', base: 4, unit: 'cl' },
      { label: 'Sirop de vanille', base: 1.5, unit: 'cl' },
      { label: 'Jus de fruit de la passion (ou d\'ananas)', base: 5, unit: 'cl' },
      { label: 'Jus de citron vert', base: 1, unit: 'cl' },
    ],
    steps: [
      { text: 'Munis-toi de ton meilleur shaker.' },
      { text: 'Ajoute le rhum blanc, le sirop de vanille, le jus choisi (si t\'as pris l\'ananas, on se sait ;)) et le jus de citron vert.' },
      { text: 'Shake énergiquement pendant environ 8 secondes.' },
      { text: 'Verse dans un verre.' },
      { text: 'Bonus : décore avec une demi-orange caramélisée sur le dessus.' },
      { text: 'Level supérieur : sers un shot de prosecco sur le côté pour te rincer la bouche entre chaque gorgée.' },
    ],
    notes: 'L\'alcool est à consommer avec modération (non, tu n\'as pas d\'amis qui s\'appelle "modération").',
  },
  {
    id: 'liqueur-kiwi',
    type: 'recipe',
    category: 'Boissons',
    title: 'Liqueur de Kiwi',
    titleBase: 'Liqueur',
    titleItalic: 'de Kiwi',
    time: '1 mois',
    difficulty: 'Facile',
    tags: ['~20°', '~1,5 L'],
    illustration: 'kiwi',
    ingredients: [
      { label: '12 kiwis' },
      { label: '100g de sucre' },
      { label: '1L d\'alcool pour fruits à 35%' },
      { label: '1 grand bocal hermétique' },
    ],
    steps: [
      { text: 'Enlève la chair des kiwis et balance tout dans une casserole.' },
      { text: 'Mixe les kiwis le plus finement possible pour obtenir une bonne purée.' },
      { text: 'Ajoute ton sucre et fais chauffer jusqu\'à ébullition en mélangeant de temps en temps.' },
      { text: 'Coupe le feu et laisse refroidir un peu.' },
      { text: 'Balance tout dans le bocal hermétique et ajoute ton alcool.' },
      { text: 'Ferme le bocal et mélange bien.' },
      { text: 'Dépose-le dans un endroit frais et sombre — idéalement une cave — pendant 1 mois.' },
      { text: 'Les 2 premières semaines : secoue tous les 2-3 jours.' },
      { text: 'Les 2 dernières semaines : secoue tous les 4-5 jours.' },
      { text: 'Filtre une première fois au tamis, puis une seconde fois au torchon ou au filtre à café si t\'as la foi (voire torchon puis filtre à café si besoin).' },
      { text: 'Déguste ta liqueur de kiwi en cocktail ou nature, chef.' },
    ],
    notes: 'L\'alcool est à consommer avec modération (non, tu n\'as pas d\'amis qui s\'appelle "modération").',
  },
  {
    id: 'creme-brulee',
    type: 'recipe',
    category: 'Boissons',
    title: 'Crème Brûlée',
    titleBase: 'Crème Brûlée',
    time: '5 min',
    difficulty: 'Facile',
    servings: 1,
    illustration: 'creme-brulee',
    ingredients: [
      { label: 'Vodka', base: 4, unit: 'cl' },
      { label: 'Liqueur 43', base: 2, unit: 'cl' },
      { label: 'Crème épaisse', base: 2, unit: 'cl' },
      { label: 'Sirop de vanille', base: 1, unit: 'cl' },
      { label: 'Œuf', base: 1 },
      { label: 'Sucre glace (pour la déco)' },
    ],
    steps: [
      { text: 'Munis-toi de notre ami le shaker.' },
      { text: 'Ajoute l\'intégralité des ingrédients sauf le sucre glace et shake très énergiquement pendant 10–15 secondes — sans glaçons.' },
      { text: 'Ajoute des glaçons et reshake pendant 3–4 secondes.' },
      { text: 'Verse dans le verre de ton choix.' },
      { text: 'Tamise délicatement le sucre glace par-dessus la mousse — attention, ça ne fonctionne que s\'il y a une belle mousse en surface.' },
      { text: 'Passe un coup de chalumeau sur le sucre pour le transformer en caramel et déguste.' },
    ],
    notes: 'L\'œuf sert à créer la mousse — sans elle, pas de caramel.',
  },
  {
    id: 'psychedelic-frog',
    type: 'recipe',
    category: 'Boissons',
    title: 'Psychedelic Frog',
    titleBase: 'Psychedelic Frog',
    time: '5 min',
    difficulty: 'Facile',
    servings: 1,
    illustration: 'psychedelic-frog',
    ingredients: [
      { label: 'Rhum coco (ou Malibu)', base: 3, unit: 'cl' },
      { label: 'Midori (liqueur de melon)', base: 3, unit: 'cl' },
      { label: 'Amaretto', base: 3, unit: 'cl' },
      { label: 'Curaçao', base: 1.5, unit: 'cl' },
      { label: 'Jus d\'ananas', base: 6, unit: 'cl' },
      { label: 'Limonade', base: 1, unit: 'trait de' },
    ],
    steps: [
      { text: 'Munis-toi de notre ami le shaker.' },
      { text: 'Ajoute l\'intégralité des ingrédients sauf la limonade.' },
      { text: 'Ajoute des glaçons et shake très énergiquement pendant 10 secondes.' },
      { text: 'Verse dans le verre de ton choix.' },
      { text: 'Complète avec un trait de limonade (pas trop, il ne faudrait pas noyer le cocktail).' },
    ],
    notes: 'Personnellement je le trouve banger.',
  },
  {
    id: 'pink-panther',
    type: 'recipe',
    category: 'Boissons',
    title: 'Pink Panther',
    titleBase: 'Pink Panther',
    time: '5 min',
    difficulty: 'Facile',
    servings: 1,
    illustration: 'pink-panther',
    ingredients: [
      { label: 'Gin', base: 2, unit: 'cl' },
      { label: 'Vodka', base: 2, unit: 'cl' },
      { label: 'Grenadine', base: 1, unit: 'cl' },
      { label: 'Jus de citron vert', base: 1, unit: 'cl' },
      { label: 'Sirop de canne', base: 1, unit: 'cl' },
      { label: 'Blanc d\'œuf', base: 1 },
    ],
    steps: [
      { text: 'Munis-toi de ton fidèle shaker.' },
      { text: 'Ajoute l\'intégralité des ingrédients et shake très énergiquement pendant 10 secondes.' },
      { text: 'Ajoute quelques glaçons et reshake pendant 4 secondes.' },
      { text: 'Sers dans le verre de ton choix et déguste.' },
    ],
    notes: 'Je sais que le blanc d\'œuf peut faire peur au début, mais ça améliore de fou la texture du cocktail et en plus ça apporte DES PROTÉINES !',
  },
]

export const boissonsCategories = [
  {
    id: 'cocktails',
    label: 'Cocktails',
    fullLabel: 'Cocktails & shakers',
    entryIds: ['mai-tai', 'porn-star', 'pink-panther', 'creme-brulee', 'psychedelic-frog'],
    color: '#00d4b8',
  },
  {
    id: 'liqueurs',
    label: 'Liqueurs',
    fullLabel: 'Liqueurs maison',
    entryIds: ['limoncello', 'liqueur-kiwi'],
    color: '#f4c542',
  },
]

export function getBoissonsFilteredEntries(filterId) {
  if (!filterId) return boissonsEntries
  const cat = boissonsCategories.find((c) => c.id === filterId)
  if (cat) return boissonsEntries.filter((e) => cat.entryIds.includes(e.id))
  return boissonsEntries
}
